name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.53.1-focal 
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.7"

      - name: Install deps (node & electron already inside container)
        run: bun install --frozen-lockfile

      - name: Install system libs for Electron
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 libnss3 libasound2 libatk-bridge2.0-0 \
            libx11-xcb1 libxss1 libxkbcommon0 libxext6 libdrm2 libgbm1

      - name: Run Playwright tests
        run: bunx playwright test

      - name: Upload HTML report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30